### ISSUE TITLE
Embed index type into variant record

### ISSUE THREAD

**Issue by jklmnn** [Componolit/gneiss#135]
Currently the `Session_Index` type is a range type with a default invalid value of `0`. The problem is that the user can still use the invalid value for their meta data and therefore get undesired behaviour. The fix is to embed the actual index type into a container and make it false by default:
```Ada
type Session_Index is range 0 .. 2 ** 24 - 1 with
   Size => 24;
type Session_Index_Option (Valid : Boolean) is record
   case Valid is
      when True =>
         Index : Session_Index;
      when False =>
         null;
   end case;
end record;

for Session_Index_Option use record
   Index at 0 range  0 .. 23;
   Valid at 0 range 24 .. 31;
end record;
```
Since the index type should be able to be used in Platform code, too, it is fixed to 32 bit and little endian.

**Comment by senier** [comment]
Can this be closed?
