### ISSUE TITLE
ICMP Demo

### ISSUE THREAD

**Issue by jklmnn** [Componolit/gneiss#171]
Demo application to generate, send, receive and parse an ICMP Echo/Reply with Gneiss and RecordFlux.

**Comment by jklmnn** [comment]
Fixed by #181.

**Comment by senier** [comment]
We cannot consider this done due to Componolit/RecordFlux#174

**Comment by jklmnn** [comment]
Can this be closed now since https://github.com/Componolit/RecordFlux/issues/174 and https://github.com/Componolit/gravel/pull/13 have been merged?

**Comment by senier** [comment]
Yes.
