### ISSUE TITLE
Update to CE 2020

### ISSUE THREAD

**Issue by senier** [Componolit/gneiss#178]

**Comment by jklmnn** [comment]
This needs https://github.com/Componolit/SXML/issues/81.

**Comment by jklmnn** [comment]
The proofs for the global state of a component are mutually exclusive. `Component.Main.Platform` needs to be in the initialized states in `Component` for GNAT CE 2020. For GNAT CE 2019 it must not be inside the initialized states. I assume we want to make GNAT CE 2020 the default.

**Comment by senier** [comment]
Yes

**Comment by jklmnn** [comment]
Okay the problem is not only when proving but also that the version that GNAT CE 2020 is able to prove does not compile on any older compiler.

**Comment by jklmnn** [comment]
Closed by #179.
